//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shadowsocks_Windows_Local.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orchid")]
        public global::System.Drawing.Color SystrayIconFast {
            get {
                return ((global::System.Drawing.Color)(this["SystrayIconFast"]));
            }
            set {
                this["SystrayIconFast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LimeGreen")]
        public global::System.Drawing.Color SystrayIconGood {
            get {
                return ((global::System.Drawing.Color)(this["SystrayIconGood"]));
            }
            set {
                this["SystrayIconGood"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color SystrayIconSlow {
            get {
                return ((global::System.Drawing.Color)(this["SystrayIconSlow"]));
            }
            set {
                this["SystrayIconSlow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Coral")]
        public global::System.Drawing.Color SystrayIconBad {
            get {
                return ((global::System.Drawing.Color)(this["SystrayIconBad"]));
            }
            set {
                this["SystrayIconBad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("33, 37, 41")]
        public global::System.Drawing.Color SystrayIconDefault {
            get {
                return ((global::System.Drawing.Color)(this["SystrayIconDefault"]));
            }
            set {
                this["SystrayIconDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("485, 400")]
        public global::System.Drawing.Size SettingWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["SettingWindowSize"]));
            }
            set {
                this["SettingWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableDynamicSystrayIcon {
            get {
                return ((bool)(this["EnableDynamicSystrayIcon"]));
            }
            set {
                this["EnableDynamicSystrayIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SOCKS5_Enabled {
            get {
                return ((bool)(this["SOCKS5_Enabled"]));
            }
            set {
                this["SOCKS5_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SOCKS5_Share {
            get {
                return ((bool)(this["SOCKS5_Share"]));
            }
            set {
                this["SOCKS5_Share"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2080")]
        public ushort SOCKS5_Port {
            get {
                return ((ushort)(this["SOCKS5_Port"]));
            }
            set {
                this["SOCKS5_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HTTP_Enabled {
            get {
                return ((bool)(this["HTTP_Enabled"]));
            }
            set {
                this["HTTP_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HTTP_Share {
            get {
                return ((bool)(this["HTTP_Share"]));
            }
            set {
                this["HTTP_Share"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8080")]
        public ushort HTTP_Port {
            get {
                return ((ushort)(this["HTTP_Port"]));
            }
            set {
                this["HTTP_Port"] = value;
            }
        }
    }
}
